### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by wgregorian**
It made sense to create the directories and enable the virtual sites for me. Wondering if you think it's a good idea?

### CODE REVIEW

**Comment by wgregorian** [comment]
@pjan I was reviewing my changes from 5 months ago, I believe the defaults are already in place in README for this PR since it re-uses all existing vars. Have I missed something really obvious?

**Comment by soupdiver** [comment]
I've added a similar change for myself but introduced a variable `enabled_sites`. Which links from `sites-available` to `sites-enabled` based on the name entry.
But you wouldn't have to delete the while site definition if you want to disable the site.
What you think about this?

**Comment by otakup0pe** [comment]
I would also prefer the distinction between enabled and available sites to be represented by different variables.

**Comment by soupdiver** [comment]
Ability do enable/disable sites was introduced with https://github.com/ANXS/nginx/pull/27.
What do you think about creating the directories for the enabled sites?
In my opinion this should be handled by the deployment process of the site and not by this nginx role. Also the desired path could differ from `{{nginx_www_dir}}/{{item.server.name}}`
@pjan @otakup0pe

**Comment by farridav** [comment]
closing this in favour of https://github.com/ANXS/nginx/pull/29

**Pull request closed without merging**
