### PR TITLE
Add geoip module support

### PR DESCRIPTION
**Pull request by welcoMattic**
[Issue #4](https://github.com/ANXS/nginx/issues/4)
- this PR fix the OpenSSL version upgrade (https://github.com/welcoMattic/nginx/commit/adce707ee524289591dc78affbcaedcce72b63a9), required to pass the build step, because previous version of OpenSSL is not online anymore.

### CODE REVIEW

**Comment by welcoMattic** [comment]
I don't understand why Travis build failed. It pass in my local env.

**Comment by welcoMattic** [comment]
@pjan up

**Comment by otakup0pe** [comment]
The first travis pass succeeds. The idempotency test fails. After fixing the `vagrant-inventory` locally I see two changes on the second vagrant run.

**Comment by welcoMattic** [comment]
I just fix the last version number of OpenSSL here : https://github.com/welcoMattic/nginx/pull/1. I pull it into my geoip to avoid build failing.

**Comment by welcoMattic** [comment]
@otakup0pe what's your testing workflow on local. I can't reproduce TravisCI workflow with success?

**Comment by welcoMattic** [comment]
@otakup0pe @pjan LGTM

**Comment by otakup0pe** [comment]
Did we merge this in a different PR? If not, let's get the conflicts sorted so we can merge.

**Comment by welcoMattic** [comment]
It was merged in https://github.com/ANXS/nginx/pull/66. We can close this PR, I think

**Pull request closed without merging**
