### PR TITLE
Feature/meta

### PR DESCRIPTION
**Pull request by welcoMattic**
Make hostname update as optional

Depends on https://github.com/ANXS/nginx/pull/46

### CODE REVIEW

**Comment by soupdiver** [comment]
ok the bump of the OpenSSL version is in the current master.
Could you somehow split/clean the remaining features like geoip module?

**Comment by welcoMattic** [comment]
@soupdiver Ok, I'll split features. Sorry about this, I fixed openssl version quickly in at office.

**Comment by welcoMattic** [comment]
@soupdiver LGTM, you too ?

**Comment by pjan** [comment]
looks ok to me, but I'd like @soupdiver to confirm.

Any chance you could squash the commits in order to keep the commit-history of master reasonably clean-ish?

**Comment by welcoMattic** [comment]
@pjan Hmm, don't know how can I rewrite the remote git history ... Do you know how ?

**Comment by pjan** [comment]
It's in the repository you own:

I believe you can try (on this branch):
```
git rebase -i HEAD~30    
// interactive rebase on 30 commits. change the "pick" in line 2 to the last commit to "s" and save
// now all these commits should be squashed onto the first one

git push origin feature/meta --force
// force push it to rewrite the git history of that branch
```

**Pull request closed without merging**
