### PR TITLE
Fix relative paths (#65)

### PR DESCRIPTION
**Pull request by zemanel**
Tested with Ansible `2.0.0.2`

### CODE REVIEW

**Comment by soupdiver** [comment]
If you could get Travis to green that would be nice :)

**Comment by zemanel** [comment]
Right, i'll take a look at it.

**Comment by soupdiver** [comment]
See #78

**Comment by zemanel** [comment]
@soupdiver cool ! I did take a look at the Travis tests run but couldn't fix it.

**Comment by farridav** [comment]
Happy to take a look at this over the next couple of days :) will update

**Pull request closed without merging**
