### PR TITLE
PageSpeed optimization module

### PR DESCRIPTION
**Pull request by calvinpy**
Hi!!
Build ngx_pagespeed From Source.

### CODE REVIEW

**Comment by soupdiver** [comment]
Hey @pjan and @otakup0pe 
I just did the rebase: https://github.com/soupdiver/nginx/commits/add_pagespeed_optimization_module
The "remove" dependencies isn't included. Is there a reason to remove the dependencies?

**Comment by pjan** [comment]
Some people don't like them, so they can cherry-pick their own dependencies. I don't like to care about dependencies, and that's why they were in there in the first place.

Open to discuss changing this, if you guys feel it should.

**Comment by soupdiver** [comment]
I like the "batteries included" approach. Provide a working version including dependencies which works and if there is a need to replace components you can do it anyway.
So I would keep the dependencies because they are there for a reason

**Comment by pjan** [comment]
@soupdiver. Feel free to open your PR here, merge it, and close this one by referencing it.

**Pull request closed without merging**
