### PR TITLE
add geoip module support

### PR DESCRIPTION
**Pull request by TinOo512**
https://github.com/ANXS/nginx/issues/4

We moved the work of @welcoMattic (https://github.com/ANXS/nginx/pull/46) in our organisation.

So this PR is now split and clean.

### CODE REVIEW

**Comment by farridav** [comment]
Nice contribution! do we want to default this to on? its going to cause everyone using this role that is building from source to have to recompile their nginx installation (that includes me) or add `nginx_geoip:·'off'` into their playbooks

I suppose the bigger question here is do we want to add all new features into the nginx build by default @otakup0pe @soupdiver @pjan?

**Comment by otakup0pe** [comment]
My preference is for the default behavior when adding (most) features is to remain the same. To that end, this (and other modules) should probably not be enabled by default.

**Comment by farridav** [comment]
If we can get this feature disabled by default, happy to get it merged in :) separate to this, we will add a note to the README specifying the process for adding new features going forwards :)

**Comment by TinOo512** [comment]
I renamed the key in the `nginx_source_modules_included` and I disabled the module by default.

But maybe we should remove it from `nginx_source_modules_included` because even if it's disable it will be include in the nginx build.

Also let me know if I should squash my commits :)

**Comment by farridav** [comment]
I guess its ok to leave it in the source modules because anyone choosing to build from source, will probably be doing it so they can use their own compile flags within `nginx_source_modules_included` so will not be affected by this addition... squashing into the first commit would be awesome! keep the mainline clean... will keep a close eye on this and aim to get this in as soon as squashed.. thanks for your contribution :)

**Comment by TinOo512** [comment]
Done :)

**Pull request merged**
