### PR TITLE
add PageSpeed optimization module

### PR DESCRIPTION
**Pull request by soupdiver**
Fixes #18

### CODE REVIEW

**Comment by soupdiver** [comment]
@pjan Ok opened this PR. What do you think about my concern about `build-essential`?

**Comment by farridav** [comment]
The implementation seems sane to me, and AFAIK this role already has build essential as a dep .https://github.com/soupdiver/nginx/blob/add_pagespeed_optimization_module/meta/main.yml#L19

**Comment by otakup0pe** [comment]
Yeah we can take out the explicit reference to installing the `build-essential` package since we already bring in the role.

Otherwise LGTM, although I haven't tried spinning this up yet.

**Comment by soupdiver** [comment]
Oh yeah you guys are right.
I've updated the PR and removed the installation of the package

**Comment by soupdiver** [comment]
```
bash
/usr/local/nginx/nginx-1.5.3/sbin/nginx -V
nginx version: nginx/1.5.3
built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
configure arguments: --prefix=/usr/local/nginx/nginx-1.5.3 --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/local/nginx/nginx-1.5.3/sbin/nginx --add-module=/tmp/ngx_pagespeed --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module
```
@otakup0pe or @farridav feel free to merge :)

**Comment by otakup0pe** [comment]
Sorry I didn't poke this earlier. It's failing in Vagrant because of old apt caches. Needs the ANXS.apt role as well.

**Comment by soupdiver** [comment]
@otakup0pe @farridav I think the problem was introduced with https://github.com/ANXS/nginx/commit/4cd732d95e0e95b97733140f428d28ff492e7dc3
That removed some packages from getting installed when running `test.yml`
These packages are required and would get installed via other roles but that mechanism is not present in the way we test with vagrant. We just include the `main.yml` task and not apply the role including roles in depends on. So these packages are missing and compiling of the module fails.

I can either add the needed packages again to `test.yml` or we could test in a way that roles are really applied instead just pulling the main task.

**Comment by otakup0pe** [comment]
Hmm. I'm not using test.yml when testing in vagrant. Maybe we need to look into how the vagrantfiles work with role dependencies ?

**Comment by soupdiver** [comment]
@otakup0pe Yeah... right now role dependencies are totally ignored because we just pull in the `tasks/main.yml` and that's it

**Comment by otakup0pe** [comment]
Merging this. Will handle the vagrant dependencies issue in another PR.

**Pull request merged**
